package com.musica.catalogo.model;

import javax.persistence.*;

/*
* Entities in JPA are nothing but POJOs representing data that can be persisted to the database. An entity represents a table stored in a database.
* Every instance of an entity represents a row in the table.  So let's define it by making use of the @Entity annotation. We must specify this annotation
* at the class level. We must also ensure that the entity has a no-arg constructor and a primary key.
* */

@Entity
@Table(name ="records")
public class Vinilo {
    /*
    * The @Idannotation is inherited from javax.persistence.Id， indicating the member field below is the primary key of current entity.
    * Hence your Hibernate and spring framework as well as you can do some reflect works based on this annotation. for details please check javadoc for Id
    * The @GeneratedValue annotation is to configure the way of increment of the specified column(field).
    * For example when using Mysql, you may specify auto_increment in the definition of table to make it self-incremental, and then use
    *  @GeneratedValue(strategy = GenerationType.IDENTITY)
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // the primary key
    @Column(name = "record_name")  // @Column annotation is used for Adding the column the name in the table of a particular MySQL database.
    private String record_Name; // the name of the record
    @Column(name = "band_name")
    private String band_Name; // the name of the band
    @Column(name = "record_Year")
    private Integer record_Year; // year of edition

    public Vinilo() { // need to generate an empty constructor
    }

    public Vinilo(String record_Name, String band_Name, Integer record_Year) {
        super(); // to add the autogenerated id?
        this.record_Name = record_Name;
        this.band_Name = band_Name;
        this.record_Year = record_Year;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRecord_Name() {
        return record_Name;
    }

    public void setRecord_Name(String record_Name) {
        this.record_Name = record_Name;
    }

    public String getBand_name() {
        return band_Name;
    }

    public void setBand_name(String band_name) {
        this.band_Name = band_name;
    }

    public Integer getRecord_Year() {
        return record_Year;
    }

    public void setYear(Integer record_Year) {
        this.record_Year = record_Year;
    }

}
